import { Book } from "./OneBook";
import { getDate } from "./lib/dates";
import { BookYearComposition } from "./BookYearComposition";

const books: Book[] = [
  {
    num: 1,
    imagePath: "2025/01-near-to-the-wild-heart.jpg",
    title: "Near to the Wild Heart",
    author: "Clarice Lispector",
    dateFinished: getDate("2025-01-03"),
    numPages: 194,
  },
  {
    num: 2,
    imagePath: "2025/02-septology.jpg",
    title: "Septology",
    author: "Jon Fosse",
    dateFinished: getDate("2025-01-25"),
    numPages: 672,
  },
  {
    num: 3,
    imagePath: "2025/03-suttree.jpg",
    title: "Suttree",
    author: "Cormac McCarthy",
    dateFinished: getDate("2025-02-09"),
    numPages: 471,
  },
  {
    num: 4,
    imagePath: "2025/04-berg.jpg",
    title: "Berg",
    author: "Ann Quin",
    dateFinished: getDate("2025-02-14"),
    numPages: 153,
  },
  {
    num: 5,
    imagePath: "2025/05-overstory.jpg",
    title: "The Overstory",
    author: "Richard Powers",
    dateFinished: getDate("2025-02-24"),
    numPages: 502,
  },
  {
    num: 6,
    imagePath: "2025/06-the-elementary-particles.jpg",
    title: "The Elementary Particles",
    author: "Michel Houellebecq",
    dateFinished: getDate("2025-03-02"),
    numPages: 272,
  },
  {
    num: 7,
    imagePath: "2025/07-satantango.jpg",
    title: "Satantango",
    author: "László Krasznahorkai",
    dateFinished: getDate("2025-03-14"),
    numPages: 288,
  },
  {
    num: 8,
    imagePath: "2025/08-resuscitation-of-a-hanged-man.jpg",
    title: "Resuscitation of a Hanged Man",
    author: "Denis Johnson",
    dateFinished: getDate("2025-03-23"),
    numPages: 256,
  },
  {
    num: 9,
    imagePath: "2025/09-motorman.jpg",
    title: "Motorman",
    author: "David Ohle",
    dateFinished: getDate("2025-04-06"),
    numPages: 117,
  },
  {
    num: 10,
    imagePath: "2025/10-solenoid.jpg",
    title: "Solenoid",
    author: "Mircea Cărtărescu",
    dateFinished: getDate("2025-04-26"),
    numPages: 639,
  },
  {
    num: 11,
    imagePath: "2025/11-under-the-volcano.jpg",
    title: "Under the Volcano",
    author: "Malcolm Lowry",
    dateFinished: getDate("2025-05-09"),
    numPages: 423,
  },
  {
    num: 12,
    imagePath: "2025/12-the-rings-of-saturn.jpg",
    title: "The Rings of Saturn",
    author: "W.G. Sebald",
    dateFinished: getDate("2025-05-12"),
    numPages: 296,
  },
  {
    num: 13,
    imagePath: "2025/13-in-the-miso-soup.jpg",
    title: "In the Miso Soup",
    author: "Ryū Murakami",
    dateFinished: getDate("2025-05-16"),
    numPages: 217,
  },
  {
    num: 14,
    imagePath: "2025/14-a-little-lumpen-novelita.jpg",
    title: "A Little Lumpen Novelita",
    author: "Roberto Bolaño",
    dateFinished: getDate("2025-05-16"),
    numPages: 128,
  },
  {
    num: 15,
    imagePath: "2025/15-just-kids.jpg",
    title: "Just Kids",
    author: "Patti Smith",
    dateFinished: getDate("2025-05-20"),
    numPages: 306,
  },
  {
    num: 16,
    imagePath: "2025/16-piranesi.jpg",
    title: "Piranesi",
    author: "Susanna Clarke",
    dateFinished: getDate("2025-05-23"),
    numPages: 272,
  },
  {
    num: 17,
    imagePath: "2025/17-the-birds.jpg",
    title: "The Birds",
    author: "Tarjei Vesaas",
    dateFinished: getDate("2025-05-25"),
    numPages: 301,
  },
  {
    num: 18,
    imagePath: "2025/18-boons-and-the-camp.jpg",
    title: "Boons & The Camp",
    author: "David Ohle",
    dateFinished: getDate("2025-05-26"),
    numPages: 100,
  },
  {
    num: 19,
    imagePath: "2025/19-demon-copperhead.jpg",
    title: "Demon Copperhead",
    author: "Barbara Kingsolver",
    dateFinished: getDate("2025-06-03"),
    numPages: 560,
  },
  {
    num: 20,
    imagePath: "2025/20-approaching-oblivion.jpg",
    title: "Approaching Oblivion",
    author: "Harlan Ellison",
    dateFinished: getDate("2025-06-06"),
    numPages: 184,
  },
  {
    num: 21,
    imagePath: "2025/21-song-for-the-unraveling-of-the-world.jpg",
    title: "Song for the Unraveling of the World",
    author: "Brian Evenson",
    dateFinished: getDate("2025-06-08"),
    numPages: 208,
  },
  {
    num: 22,
    imagePath: "2025/22-i-who-have-never-known-men.jpg",
    title: "I Who Have Never Known Men",
    author: "Jacqueline Harpman",
    dateFinished: getDate("2025-06-18"),
    numPages: 184,
  },
  {
    num: 23,
    imagePath: "2025/23-the-employees.jpg",
    title: "The Employees",
    author: "Olga Ravn",
    dateFinished: getDate("2025-07-03"),
    numPages: 125,
  },
  {
    num: 24,
    imagePath: "2025/24-frog.jpg",
    title: "Frog",
    author: "Stephen Dixon",
    dateFinished: getDate("2025-07-07"),
    numPages: 769,
  },
  {
    num: 25,
    imagePath: "2025/25-hit-parade-of-tears.jpg",
    title: "Hit Parade of Tears",
    author: "Izumi Suzuki",
    dateFinished: getDate("2025-07-09"),
    numPages: 288,
  },
  {
    num: 26,
    imagePath: "2025/26-invisible-cities.jpg",
    title: "Invisible Cities",
    author: "Italo Calvino",
    dateFinished: getDate("2025-07-10"),
    numPages: 165,
  },
  {
    num: 27,
    imagePath: "2025/27-cities-ive-never-lived-in.jpg",
    title: "Cities I've Never Lived In",
    author: "Sara Majka",
    dateFinished: getDate("2025-07-18"),
    numPages: 160,
  },
  {
    num: 28,
    imagePath: "2025/28-vineland.jpg",
    title: "Vineland",
    author: "Thomas Pynchon",
    dateFinished: getDate("2025-07-31"),
    numPages: 385,
  },
  {
    num: 29,
    imagePath: "2025/29-roadside-picnic.jpg",
    title: "Roadside Picnic",
    author: "Arkady Strugatsky",
    dateFinished: getDate("2025-08-01"),
    numPages: 209,
  },
  {
    num: 30,
    imagePath: "2025/30-burning-chrome.jpg",
    title: "Burning Chrome",
    author: "William Gibson",
    dateFinished: getDate("2025-08-10"),
    numPages: 204,
  },
  {
    num: 31,
    imagePath: "2025/31-the-metamorphosis-of-prime-intellect.jpg",
    title: "The Metamorphosis of Prime Intellect",
    author: "Roger Williams",
    dateFinished: getDate("2025-08-13"),
    numPages: 175,
  },
  {
    num: 32,
    imagePath: "2025/32-absalom-absalom.jpg",
    title: "Absalom, Absalom!",
    author: "William Faulkner",
    dateFinished: getDate("2025-08-24"),
    numPages: 316,
  },
  {
    num: 33,
    imagePath: "2025/33-the-inverted-world.jpg",
    title: "The Inverted World",
    author: "Christopher Priest",
    dateFinished: getDate("2025-08-30"),
    numPages: 322,
  },
  {
    num: 34,
    imagePath: "2025/34-cities-of-the-plain.jpg",
    title: "Cities of the Plain",
    author: "Cormac McCarthy",
    dateFinished: getDate("2025-09-04"),
    numPages: 293,
  },
  {
    num: 35,
    imagePath: "2025/35-the-cabin-at-the-end-of-the-world.jpg",
    title: "The Cabin at the End of the World",
    author: "Paul Tremblay",
    dateFinished: getDate("2025-09-06"),
    numPages: 288,
  },
  {
    num: 36,
    imagePath: "2025/36-too-loud-a-solitude.jpg",
    title: "Too Loud a Solitude",
    author: "Bohumil Hrabal",
    dateFinished: getDate("2025-09-07"),
    numPages: 102,
  },
  {
    num: 37,
    imagePath: "2025/37-pedro-paramo.jpg",
    title: "Pedro Páramo",
    author: "Juan Rulfo",
    dateFinished: getDate("2025-09-11"),
    numPages: 128,
  },
  {
    num: 38,
    imagePath: "2025/38-the-dying-earth.jpg",
    title: "The Dying Earth",
    author: "Jack Vance",
    dateFinished: getDate("2025-09-15"),
    numPages: 156,
  },
  {
    num: 39,
    imagePath: "2025/39-the-eyes-of-the-overworld.jpg",
    title: "The Eyes of the Overworld",
    author: "Jack Vance",
    dateFinished: getDate("2025-09-28"),
    numPages: 190,
  },
  {
    num: 40,
    imagePath: "2025/40-blood-music.jpg",
    title: "Blood Music",
    author: "Greg Bear",
    dateFinished: getDate("2025-10-21"),
    numPages: 256,
  },
  {
    num: 41,
    imagePath: "2025/41-schattenfroh.jpg",
    title: "Schattenfroh",
    author: "Michael Lentz",
    dateFinished: getDate("2025-11-01"),
    numPages: 1001,
  },
  {
    num: 42,
    imagePath: "2025/42-the-missing-pieces.jpg",
    title: "The Missing Pieces",
    author: "Henri Lefebvre",
    dateFinished: getDate("2025-11-01"),
    numPages: 84,
  },
  {
    num: 43,
    imagePath: "2025/43-waiting-for-the-barbarians.jpg",
    title: "Waiting for the Barbarians",
    author: "J.M. Coetzee",
    dateFinished: getDate("2025-11-01"),
    numPages: 156,
  },
  {
    num: 44,
    imagePath: "2025/44-weak-in-comparison-to-dreams.jpg",
    title: "Weak in Comparison to Dreams",
    author: "James Elkins",
    dateFinished: getDate("2025-11-23"),
    numPages: 607,
  },
  {
    num: 45,
    imagePath: "2025/45-wittgensteins-nephew.jpg",
    title: "Wittgenstein's Nephew",
    author: "Thomas Bernhard",
    dateFinished: getDate("2025-11-26"),
    numPages: 101,
  },
  {
    num: 46,
    imagePath: "2025/46-jayber-crow.jpg",
    title: "Jayber Crow",
    author: "Wendell Berry",
    dateFinished: getDate("2025-11-30"),
    numPages: 363,
  },
  {
    num: 47,
    imagePath: "2025/47-trout-fishing-in-america.jpg",
    title: "Trout Fishing in America",
    author: "Richard Brautigan",
    dateFinished: getDate("2025-12-05"),
    numPages: 112,
  },
  {
    num: 48,
    imagePath: "2025/48-solaris.jpg",
    title: "Solaris",
    author: "Stanisław Lem",
    dateFinished: getDate("2025-12-10"),
    numPages: 224,
  },
  {
    num: 49,
    imagePath: "2025/49-where-the-air-is-clear.jpg",
    title: "Where the Air is Clear",
    author: "Carlos Fuentes",
    dateFinished: getDate("2025-12-26"),
    numPages: 224,
  },
];

const stackImagePaths: string[] = [];

export function Books2025Composition() {
  return (
    <BookYearComposition
      id="2025"
      title="2025 Reads"
      books={books}
      audioPath="music/background-music-438663.mp3"
      stackImagePaths={stackImagePaths}
      individualBookDurationInSeconds={2.6}
    />
  );
}
